# Generated by Django 2.0.6 on 2018-07-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_id', models.CharField(max_length=200)),
                ('enterprise_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('notify_time', models.DateTimeField()),
                ('reseive_date', models.CharField(max_length=200)),
                ('fee_status', models.CharField(max_length=200)),
                ('fee_date', models.DateField()),
                ('test_date', models.DateField()),
                ('classify', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('crawl_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ik', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField()),
                ('last_craw_time', models.DateTimeField()),
            ],
        ),
    ]
