# Generated by Django 2.0.6 on 2018-07-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='ik',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_craw_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='update_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
