# Generated by Django 2.0.6 on 2018-07-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20180718_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='last_craw_time',
        ),
        migrations.RemoveField(
            model_name='source',
            name='update_time',
        ),
    ]
